### PR TITLE
close #270 rival function bug

### LINKED ISSUE #270: [production][rivals#remove] NoMethodError: undefined method `delete' for nil:NilClass
[See this exception on Errbit](http://iidx12.herokuapp.com/apps/55544ca4386532000f000000/problems/560c1d67353733000c000075)
# NoMethodError: undefined method `delete&#39; for nil:NilClass #
### URL ###
[http://iidx12.tk/abilitysheet/rival/remove/3223-5186](http://iidx12.tk/abilitysheet/rival/remove/3223-5186)"
### Where ###
rivals#remove

### Occured ###
Oct 01  2:35am

### Similar ###
0

## Params ##
~~~
{
  &quot;action&quot; =&gt; &quot;remove&quot;,
  &quot;controller&quot; =&gt; &quot;rivals&quot;,
  &quot;id&quot; =&gt; &quot;3223-5186&quot;
}
~~~

## Session ##
~~~
{
  &quot;_csrf_token&quot; =&gt; &quot;[FILTERED]&quot;,
  &quot;flash&quot; =&gt; {
    &quot;discard&quot; =&gt; &quot;[\&quot;notice\&quot;]&quot;,
    &quot;flashes&quot; =&gt; {
      &quot;notice&quot; =&gt; &quot;ライバル(3223-5186)を追加しました&quot;
    }
  },
  &quot;session_id&quot; =&gt; &quot;3c72b57247944c4db338ad26859bfb9d&quot;,
  &quot;warden_user_user_key&quot; =&gt; &quot;[[\&quot;1\&quot;], \&quot;$2a$10$2hlxk2XDEXQmlJ45K.YCMu\&quot;]&quot;
}
~~~

## Backtrace ##
~~~
26:  app/models/concerns/rival.rb -> **remove_rival**
38:  app/controllers/rivals_controller.rb -> **remove**
4:  [GEM_ROOT]/gems/actionpack-4.2.4/lib/action_controller/metal/implicit_render.rb -> **send_action**
198:  [GEM_ROOT]/gems/actionpack-4.2.4/lib/abstract_controller/base.rb -> **process_action**
10:  [GEM_ROOT]/gems/actionpack-4.2.4/lib/action_controller/metal/rendering.rb -> **process_action**
20:  [GEM_ROOT]/gems/actionpack-4.2.4/lib/abstract_controller/callbacks.rb -> **block in process_action**
117:  [GEM_ROOT]/gems/activesupport-4.2.4/lib/active_support/callbacks.rb -> **call**
117:  [GEM_ROOT]/gems/activesupport-4.2.4/lib/active_support/callbacks.rb -> **call**
555:  [GEM_ROOT]/gems/activesupport-4.2.4/lib/active_support/callbacks.rb -> **block (2 levels) in compile**
505:  [GEM_ROOT]/gems/activesupport-4.2.4/lib/active_support/callbacks.rb -> **call**
505:  [GEM_ROOT]/gems/activesupport-4.2.4/lib/active_support/callbacks.rb -> **call**
92:  [GEM_ROOT]/gems/activesupport-4.2.4/lib/active_support/callbacks.rb -> **__run_callbacks__**
778:  [GEM_ROOT]/gems/activesupport-4.2.4/lib/active_support/callbacks.rb -> **_run_process_action_callbacks**
81:  [GEM_ROOT]/gems/activesupport-4.2.4/lib/active_support/callbacks.rb -> **run_callbacks**
19:  [GEM_ROOT]/gems/actionpack-4.2.4/lib/abstract_controller/callbacks.rb -> **process_action**
29:  [GEM_ROOT]/gems/actionpack-4.2.4/lib/action_controller/metal/rescue.rb -> **process_action**
32:  [GEM_ROOT]/gems/actionpack-4.2.4/lib/action_controller/metal/instrumentation.rb -> **block in process_action**
164:  [GEM_ROOT]/gems/activesupport-4.2.4/lib/active_support/notifications.rb -> **block in instrument**
20:  [GEM_ROOT]/gems/activesupport-4.2.4/lib/active_support/notifications/instrumenter.rb -> **instrument**
164:  [GEM_ROOT]/gems/activesupport-4.2.4/lib/active_support/notifications.rb -> **instrument**
30:  [GEM_ROOT]/gems/actionpack-4.2.4/lib/action_controller/metal/instrumentation.rb -> **process_action**
250:  [GEM_ROOT]/gems/actionpack-4.2.4/lib/action_controller/metal/params_wrapper.rb -> **process_action**
18:  [GEM_ROOT]/gems/activerecord-4.2.4/lib/active_record/railties/controller_runtime.rb -> **process_action**
137:  [GEM_ROOT]/gems/actionpack-4.2.4/lib/abstract_controller/base.rb -> **process**
30:  [GEM_ROOT]/gems/actionview-4.2.4/lib/action_view/rendering.rb -> **process**
106:  [GEM_ROOT]/gems/rack-mini-profiler-0.9.7/lib/mini_profiler/profiling_methods.rb -> **block in profile_method**
196:  [GEM_ROOT]/gems/actionpack-4.2.4/lib/action_controller/metal.rb -> **dispatch**
13:  [GEM_ROOT]/gems/actionpack-4.2.4/lib/action_controller/metal/rack_delegation.rb -> **dispatch**
237:  [GEM_ROOT]/gems/actionpack-4.2.4/lib/action_controller/metal.rb -> **block in action**
76:  [GEM_ROOT]/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb -> **call**
76:  [GEM_ROOT]/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb -> **dispatch**
45:  [GEM_ROOT]/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb -> **serve**
43:  [GEM_ROOT]/gems/actionpack-4.2.4/lib/action_dispatch/journey/router.rb -> **block in serve**
30:  [GEM_ROOT]/gems/actionpack-4.2.4/lib/action_dispatch/journey/router.rb -> **each**
30:  [GEM_ROOT]/gems/actionpack-4.2.4/lib/action_dispatch/journey/router.rb -> **serve**
821:  [GEM_ROOT]/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb -> **call**
67:  [GEM_ROOT]/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/middleware_tracing.rb -> **call**
12:  [GEM_ROOT]/gems/rack-pjax-0.8.0/lib/rack/pjax.rb -> **call**
67:  [GEM_ROOT]/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/middleware_tracing.rb -> **call**
30:  [GEM_ROOT]/gems/newrelic_rpm-3.13.1.300/lib/new_relic/rack/agent_hooks.rb -> **traced_call**
67:  [GEM_ROOT]/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/middleware_tracing.rb -> **call**
32:  [GEM_ROOT]/gems/newrelic_rpm-3.13.1.300/lib/new_relic/rack/browser_monitoring.rb -> **traced_call**
67:  [GEM_ROOT]/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/middleware_tracing.rb -> **call**
35:  [GEM_ROOT]/gems/warden-1.2.3/lib/warden/manager.rb -> **block in call**
34:  [GEM_ROOT]/gems/warden-1.2.3/lib/warden/manager.rb -> **catch**
34:  [GEM_ROOT]/gems/warden-1.2.3/lib/warden/manager.rb -> **call**
67:  [GEM_ROOT]/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/middleware_tracing.rb -> **call**
24:  [GEM_ROOT]/gems/rack-1.6.4/lib/rack/etag.rb -> **call**
67:  [GEM_ROOT]/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/middleware_tracing.rb -> **call**
38:  [GEM_ROOT]/gems/rack-1.6.4/lib/rack/conditionalget.rb -> **call**
67:  [GEM_ROOT]/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/middleware_tracing.rb -> **call**
13:  [GEM_ROOT]/gems/rack-1.6.4/lib/rack/head.rb -> **call**
67:  [GEM_ROOT]/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/middleware_tracing.rb -> **call**
27:  [GEM_ROOT]/gems/remotipart-1.2.1/lib/remotipart/middleware.rb -> **call**
67:  [GEM_ROOT]/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/middleware_tracing.rb -> **call**
27:  [GEM_ROOT]/gems/actionpack-4.2.4/lib/action_dispatch/middleware/params_parser.rb -> **call**
67:  [GEM_ROOT]/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/middleware_tracing.rb -> **call**
260:  [GEM_ROOT]/gems/actionpack-4.2.4/lib/action_dispatch/middleware/flash.rb -> **call**
67:  [GEM_ROOT]/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/middleware_tracing.rb -> **call**
225:  [GEM_ROOT]/gems/rack-1.6.4/lib/rack/session/abstract/id.rb -> **context**
220:  [GEM_ROOT]/gems/rack-1.6.4/lib/rack/session/abstract/id.rb -> **call**
67:  [GEM_ROOT]/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/middleware_tracing.rb -> **call**
560:  [GEM_ROOT]/gems/actionpack-4.2.4/lib/action_dispatch/middleware/cookies.rb -> **call**
67:  [GEM_ROOT]/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/middleware_tracing.rb -> **call**
36:  [GEM_ROOT]/gems/activerecord-4.2.4/lib/active_record/query_cache.rb -> **call**
67:  [GEM_ROOT]/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/middleware_tracing.rb -> **call**
653:  [GEM_ROOT]/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb -> **call**
67:  [GEM_ROOT]/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/middleware_tracing.rb -> **call**
29:  [GEM_ROOT]/gems/actionpack-4.2.4/lib/action_dispatch/middleware/callbacks.rb -> **block in call**
88:  [GEM_ROOT]/gems/activesupport-4.2.4/lib/active_support/callbacks.rb -> **__run_callbacks__**
778:  [GEM_ROOT]/gems/activesupport-4.2.4/lib/active_support/callbacks.rb -> **_run_call_callbacks**
81:  [GEM_ROOT]/gems/activesupport-4.2.4/lib/active_support/callbacks.rb -> **run_callbacks**
27:  [GEM_ROOT]/gems/actionpack-4.2.4/lib/action_dispatch/middleware/callbacks.rb -> **call**
67:  [GEM_ROOT]/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/middleware_tracing.rb -> **call**
78:  [GEM_ROOT]/gems/actionpack-4.2.4/lib/action_dispatch/middleware/remote_ip.rb -> **call**
67:  [GEM_ROOT]/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/middleware_tracing.rb -> **call**
67:  [GEM_ROOT]/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/middleware_tracing.rb -> **call**
17:  [GEM_ROOT]/gems/actionpack-4.2.4/lib/action_dispatch/middleware/debug_exceptions.rb -> **call**
67:  [GEM_ROOT]/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/middleware_tracing.rb -> **call**
30:  [GEM_ROOT]/gems/actionpack-4.2.4/lib/action_dispatch/middleware/show_exceptions.rb -> **call**
67:  [GEM_ROOT]/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/middleware_tracing.rb -> **call**
38:  [GEM_ROOT]/gems/railties-4.2.4/lib/rails/rack/logger.rb -> **call_app**
22:  [GEM_ROOT]/gems/railties-4.2.4/lib/rails/rack/logger.rb -> **call**
67:  [GEM_ROOT]/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/middleware_tracing.rb -> **call**
8:  [GEM_ROOT]/gems/request_store-1.2.0/lib/request_store/middleware.rb -> **call**
67:  [GEM_ROOT]/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/middleware_tracing.rb -> **call**
21:  [GEM_ROOT]/gems/actionpack-4.2.4/lib/action_dispatch/middleware/request_id.rb -> **call**
67:  [GEM_ROOT]/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/middleware_tracing.rb -> **call**
22:  [GEM_ROOT]/gems/rack-1.6.4/lib/rack/methodoverride.rb -> **call**
67:  [GEM_ROOT]/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/middleware_tracing.rb -> **call**
18:  [GEM_ROOT]/gems/rack-1.6.4/lib/rack/runtime.rb -> **call**
67:  [GEM_ROOT]/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/middleware_tracing.rb -> **call**
28:  [GEM_ROOT]/gems/activesupport-4.2.4/lib/active_support/cache/strategy/local_cache_middleware.rb -> **call**
67:  [GEM_ROOT]/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/middleware_tracing.rb -> **call**
113:  [GEM_ROOT]/gems/rack-1.6.4/lib/rack/sendfile.rb -> **call**
67:  [GEM_ROOT]/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/middleware_tracing.rb -> **call**
67:  [GEM_ROOT]/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/middleware_tracing.rb -> **call**
276:  [GEM_ROOT]/gems/rack-mini-profiler-0.9.7/lib/mini_profiler/profiler.rb -> **call**
67:  [GEM_ROOT]/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/middleware_tracing.rb -> **call**
518:  [GEM_ROOT]/gems/railties-4.2.4/lib/rails/engine.rb -> **call**
165:  [GEM_ROOT]/gems/railties-4.2.4/lib/rails/application.rb -> **call**
67:  [GEM_ROOT]/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/middleware_tracing.rb -> **call**
66:  [GEM_ROOT]/gems/rack-1.6.4/lib/rack/urlmap.rb -> **block in call**
50:  [GEM_ROOT]/gems/rack-1.6.4/lib/rack/urlmap.rb -> **each**
50:  [GEM_ROOT]/gems/rack-1.6.4/lib/rack/urlmap.rb -> **call**
80:  [GEM_ROOT]/gems/rack-cors-0.4.0/lib/rack/cors.rb -> **call**
580:  [GEM_ROOT]/gems/unicorn-4.9.0/lib/unicorn/http_server.rb -> **process_client**
52:  [GEM_ROOT]/gems/unicorn-worker-killer-0.4.3/lib/unicorn/worker_killer.rb -> **process_client**
92:  [GEM_ROOT]/gems/unicorn-worker-killer-0.4.3/lib/unicorn/worker_killer.rb -> **process_client**
674:  [GEM_ROOT]/gems/unicorn-4.9.0/lib/unicorn/http_server.rb -> **worker_loop**
529:  [GEM_ROOT]/gems/unicorn-4.9.0/lib/unicorn/http_server.rb -> **spawn_missing_workers**
540:  [GEM_ROOT]/gems/unicorn-4.9.0/lib/unicorn/http_server.rb -> **maintain_worker_count**
294:  [GEM_ROOT]/gems/unicorn-4.9.0/lib/unicorn/http_server.rb -> **join**
209:  [GEM_ROOT]/gems/unicorn-4.9.0/bin/unicorn_rails -> **&lt;top (required)&gt;**
23:  [GEM_ROOT]/bin/unicorn_rails -> **load**
23:  [GEM_ROOT]/bin/unicorn_rails -> **&lt;main&gt;**
~~~

## Environment ##
| Key        | Value      |
|------------|------------|
| REMOTE_ADDR | 127.0.0.1 |
| REQUEST_METHOD | POST |
| REQUEST_PATH | /abilitysheet/rival/remove/3223-5186 |
| PATH_INFO | /rival/remove/3223-5186 |
| REQUEST_URI | /abilitysheet/rival/remove/3223-5186 |
| SERVER_PROTOCOL | HTTP/1.0 |
| HTTP_VERSION | HTTP/1.0 |
| HTTP_X_REAL_IP | 61.194.119.32 |
| HTTP_X_FORWARDED_FOR | 61.194.119.32 |
| HTTP_HOST | iidx12.tk |
| HTTP_CONNECTION | close |
| CONTENT_LENGTH | 0 |
| HTTP_ACCEPT | */*;q=0.5, text/javascript, application/javascript, application/ecmascript, application/x-ecmascript |
| HTTP_ORIGIN | https://iidx12.tk |
| HTTP_X_REQUESTED_WITH | XMLHttpRequest |
| HTTP_USER_AGENT | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36 |
| HTTP_REFERER | https://iidx12.tk/abilitysheet/users?utf8=%E2%9C%93&amp;query=VARNA |
| HTTP_ACCEPT_ENCODING | gzip, deflate |
| HTTP_ACCEPT_LANGUAGE | ja,en-US;q=0.8,en;q=0.6 |
| rack_url_scheme | http |
| SERVER_NAME | iidx12.tk |
| SERVER_PORT | 80 |
| QUERY_STRING |  |
| rack_hijack | #&lt;Proc:0x007f990c982130@/home/rails/deploy/abilitysheet/shared/bundle/ruby/2.2.0/gems/unicorn-4.9.0/lib/unicorn/http_request.rb:111&gt; |
| rack_multiprocess | true |
| rack_multithread | false |
| rack_run_once | false |
| rack_version | [&quot;1&quot;, &quot;2&quot;] |
| SCRIPT_NAME | /abilitysheet |
| SERVER_SOFTWARE | Unicorn 4.9.0 |
| rack_hijack? | true |
| rack_logger | #&lt;Logger:0x007f9903b84bd0&gt; |
| rack_cors | #&lt;Rack::Cors::Result:0x007f990c981fc8&gt; |
| newrelic_transaction_started | true |
| ORIGINAL_FULLPATH | /abilitysheet/rival/remove/3223-5186 |
| ORIGINAL_SCRIPT_NAME | /abilitysheet |
| action_dispatch_parameter_filter | [&quot;password&quot;, &quot;client_secret&quot;, &quot;code&quot;, &quot;token&quot;] |
| action_dispatch_redirect_filter | [] |
| action_dispatch_show_exceptions | true |
| action_dispatch_show_detailed_exceptions | false |
| action_dispatch_cookies_serializer | json |
| action_dispatch_cookies_digest |  |
| ROUTES_70147626636460_SCRIPT_NAME | /abilitysheet |
| RACK_MINI_PROFILER_ORIGINAL_SCRIPT_NAME | /abilitysheet |
| HTTP_IF_MODIFIED_SINCE |  |
| HTTP_IF_NONE_MATCH |  |
| rack_request_form_hash |  |
| rack_request_form_input | [] |
| action_dispatch_request_id | af253a3d-9839-43f2-9013-17b1f7126244 |
| action_dispatch_remote_ip | 61.194.119.32 |
| rack_request_query_string |  |
| rack_request_query_hash |  |
| warden | Warden::Proxy:70147644862480 @config={:default_scope=&gt;:user, :scope_defaults=&gt;{}, :default_strategies=&gt;{:user=&gt;[:rememberable, :database_authenticatable], :sheet=&gt;[]}, :intercept_401=&gt;false, :failure_app=&gt;#&lt;Devise::Delegator:0x007f9906820e00&gt;} |
| action_dispatch_request_path_parameters | {&quot;controller&quot;=&gt;&quot;rivals&quot;, &quot;action&quot;=&gt;&quot;remove&quot;, &quot;id&quot;=&gt;&quot;3223-5186&quot;} |
| action_dispatch_request_content_type |  |
| action_dispatch_request_request_parameters |  |
| action_dispatch_request_query_parameters |  |
| action_dispatch_request_parameters | {&quot;controller&quot;=&gt;&quot;rivals&quot;, &quot;action&quot;=&gt;&quot;remove&quot;, &quot;id&quot;=&gt;&quot;3223-5186&quot;} |
| action_dispatch_request_accepts | [&quot;text/javascript&quot;, &quot;application/ecmascript&quot;, &quot;application/x-ecmascript&quot;, &quot;*/*&quot;] |
| action_dispatch_request_formats | [&quot;text/javascript&quot;, &quot;application/ecmascript&quot;, &quot;application/x-ecmascript&quot;, &quot;*/*&quot;] |

### PR DESCRIPTION
**Pull request by 8398a7**
refs #230, #270

### CODE REVIEW

File: db/migrate/20151219233629_create_follows.rb [hunk 1]
```diff
@@ -0,0 +1,19 @@
...
+
+      t.timestamps null: false
+    end
+    add_index :follows, [:user_id, :target_user_id], unique: true
+    User.select(:id, :rival).find_each do |user|
+      next if user.rival.nil?
+      user.rival.each do |rival_iidx_id|
+        other_user_id = User.select(:id).find_by(iidxid: rival_iidx_id).id
+        next if Follow.exists?(user_id: user.id, target_user_id: other_user_id)
+        Follow.create(user_id: user.id, target_user_id: other_user_id)
```
Comment (8398a7) [inline db/migrate/20151219233629_create_follows.rb]: __[rails_best_practices]__
* isolate seed data [:ref](http://rails-bestpractices.com/posts/2010/07/24/isolating-seed-data/)

File: db/migrate/20151219233629_create_follows.rb [hunk 2]
```diff
@@ -0,0 +1,19 @@
...
+  def change
+    create_table :follows do |t|
+      t.integer :user_id
+      t.integer :target_user_id
+
+      t.timestamps null: false
+    end
+    add_index :follows, [:user_id, :target_user_id], unique: true
+    User.select(:id, :rival).find_each do |user|
+      next if user.rival.nil?
```
Comment (8398a7) [inline db/migrate/20151219233629_create_follows.rb]: __[rails_best_practices]__
* use query attribute (user.rival?) [:ref](http://rails-bestpractices.com/posts/2010/10/03/use-query-attribute/)
