### PR TITLE
close #133 fix can't open of rival page

### LINKED ISSUE #133: [production][rivals#reverse_list] NoMethodError: undefined method `[]' for nil:NilClass
[See this exception on Errbit](http://iidx12.herokuapp.com/apps/55544ca4386532000f000000/problems/559700b9326433000caa0000)
# NoMethodError: undefined method `[]&#39; for nil:NilClass #
### URL ###
[http://iidx12.tk/abilitysheet/rival/reverse_list](http://iidx12.tk/abilitysheet/rival/reverse_list)"
### Where ###
rivals#reverse_list

### Occured ###
Jul 04  6:38am

### Similar ###
3

## Params ##
~~~
{
  &quot;action&quot; =&gt; &quot;reverse_list&quot;,
  &quot;controller&quot; =&gt; &quot;rivals&quot;
}
~~~

## Session ##
~~~
{
  &quot;_csrf_token&quot; =&gt; &quot;1Qv6V3hlGKB2PCAqHOoV9BpY7qasDFvqIra3w6Ue120=&quot;,
  &quot;flash&quot; =&gt; {
    &quot;discard&quot; =&gt; &quot;[\&quot;notice\&quot;]&quot;,
    &quot;flashes&quot; =&gt; {
      &quot;notice&quot; =&gt; &quot;ログインしました。&quot;
    }
  },
  &quot;session_id&quot; =&gt; &quot;220fd4255e653a1dc4efad677c2d6f09&quot;,
  &quot;warden_user_user_key&quot; =&gt; &quot;[[\&quot;1512\&quot;], \&quot;$2a$10$Y/r1kJFcUySmjgaqkcNhvO\&quot;]&quot;
}
~~~

## Backtrace ##
~~~
16:  app/views/shared/_list.html.slim -> **block in _app_views_shared__list_html_slim__FRAGMENT__**
46:  [GEM_ROOT]/gems/activerecord-4.2.3/lib/active_record/relation/delegation.rb -> **each**
46:  [GEM_ROOT]/gems/activerecord-4.2.3/lib/active_record/relation/delegation.rb -> **each**
14:  app/views/shared/_list.html.slim -> **_app_views_shared__list_html_slim__FRAGMENT__**
145:  [GEM_ROOT]/gems/actionview-4.2.3/lib/action_view/template.rb -> **block in render**
164:  [GEM_ROOT]/gems/activesupport-4.2.3/lib/active_support/notifications.rb -> **block in instrument**
20:  [GEM_ROOT]/gems/activesupport-4.2.3/lib/active_support/notifications/instrumenter.rb -> **instrument**
164:  [GEM_ROOT]/gems/activesupport-4.2.3/lib/active_support/notifications.rb -> **instrument**
333:  [GEM_ROOT]/gems/actionview-4.2.3/lib/action_view/template.rb -> **instrument**
143:  [GEM_ROOT]/gems/actionview-4.2.3/lib/action_view/template.rb -> **render**
77:  [GEM_ROOT]/gems/rack-mini-profiler-0.9.3/lib/mini_profiler/profiling_methods.rb -> **block in profile_method**
339:  [GEM_ROOT]/gems/actionview-4.2.3/lib/action_view/renderer/partial_renderer.rb -> **render_partial**
310:  [GEM_ROOT]/gems/actionview-4.2.3/lib/action_view/renderer/partial_renderer.rb -> **block in render**
39:  [GEM_ROOT]/gems/actionview-4.2.3/lib/action_view/renderer/abstract_renderer.rb -> **block in instrument**
164:  [GEM_ROOT]/gems/activesupport-4.2.3/lib/active_support/notifications.rb -> **block in instrument**
20:  [GEM_ROOT]/gems/activesupport-4.2.3/lib/active_support/notifications/instrumenter.rb -> **instrument**
164:  [GEM_ROOT]/gems/activesupport-4.2.3/lib/active_support/notifications.rb -> **instrument**
39:  [GEM_ROOT]/gems/actionview-4.2.3/lib/action_view/renderer/abstract_renderer.rb -> **instrument**
309:  [GEM_ROOT]/gems/actionview-4.2.3/lib/action_view/renderer/partial_renderer.rb -> **render**
47:  [GEM_ROOT]/gems/actionview-4.2.3/lib/action_view/renderer/renderer.rb -> **render_partial**
35:  [GEM_ROOT]/gems/actionview-4.2.3/lib/action_view/helpers/rendering_helper.rb -> **render**
12:  [GEM_ROOT]/gems/haml-4.0.6/lib/haml/helpers/action_view_mods.rb -> **render_with_haml**
2:  app/views/rivals/reverse_list.html.slim -> **_app_views_rivals_reverse_list_html_slim__FRAGMENT__**
145:  [GEM_ROOT]/gems/actionview-4.2.3/lib/action_view/template.rb -> **block in render**
164:  [GEM_ROOT]/gems/activesupport-4.2.3/lib/active_support/notifications.rb -> **block in instrument**
20:  [GEM_ROOT]/gems/activesupport-4.2.3/lib/active_support/notifications/instrumenter.rb -> **instrument**
164:  [GEM_ROOT]/gems/activesupport-4.2.3/lib/active_support/notifications.rb -> **instrument**
333:  [GEM_ROOT]/gems/actionview-4.2.3/lib/action_view/template.rb -> **instrument**
143:  [GEM_ROOT]/gems/actionview-4.2.3/lib/action_view/template.rb -> **render**
77:  [GEM_ROOT]/gems/rack-mini-profiler-0.9.3/lib/mini_profiler/profiling_methods.rb -> **block in profile_method**
54:  [GEM_ROOT]/gems/actionview-4.2.3/lib/action_view/renderer/template_renderer.rb -> **block (2 levels) in render_template**
39:  [GEM_ROOT]/gems/actionview-4.2.3/lib/action_view/renderer/abstract_renderer.rb -> **block in instrument**
164:  [GEM_ROOT]/gems/activesupport-4.2.3/lib/active_support/notifications.rb -> **block in instrument**
20:  [GEM_ROOT]/gems/activesupport-4.2.3/lib/active_support/notifications/instrumenter.rb -> **instrument**
164:  [GEM_ROOT]/gems/activesupport-4.2.3/lib/active_support/notifications.rb -> **instrument**
39:  [GEM_ROOT]/gems/actionview-4.2.3/lib/action_view/renderer/abstract_renderer.rb -> **instrument**
53:  [GEM_ROOT]/gems/actionview-4.2.3/lib/action_view/renderer/template_renderer.rb -> **block in render_template**
61:  [GEM_ROOT]/gems/actionview-4.2.3/lib/action_view/renderer/template_renderer.rb -> **render_with_layout**
52:  [GEM_ROOT]/gems/actionview-4.2.3/lib/action_view/renderer/template_renderer.rb -> **render_template**
14:  [GEM_ROOT]/gems/actionview-4.2.3/lib/action_view/renderer/template_renderer.rb -> **render**
42:  [GEM_ROOT]/gems/actionview-4.2.3/lib/action_view/renderer/renderer.rb -> **render_template**
23:  [GEM_ROOT]/gems/actionview-4.2.3/lib/action_view/renderer/renderer.rb -> **render**
100:  [GEM_ROOT]/gems/actionview-4.2.3/lib/action_view/rendering.rb -> **_render_template**
217:  [GEM_ROOT]/gems/actionpack-4.2.3/lib/action_controller/metal/streaming.rb -> **_render_template**
83:  [GEM_ROOT]/gems/actionview-4.2.3/lib/action_view/rendering.rb -> **render_to_body**
32:  [GEM_ROOT]/gems/actionpack-4.2.3/lib/action_controller/metal/rendering.rb -> **render_to_body**
37:  [GEM_ROOT]/gems/actionpack-4.2.3/lib/action_controller/metal/renderers.rb -> **render_to_body**
25:  [GEM_ROOT]/gems/actionpack-4.2.3/lib/abstract_controller/rendering.rb -> **render**
16:  [GEM_ROOT]/gems/actionpack-4.2.3/lib/action_controller/metal/rendering.rb -> **render**
44:  [GEM_ROOT]/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb -> **block (2 levels) in render**
12:  [GEM_ROOT]/gems/activesupport-4.2.3/lib/active_support/core_ext/benchmark.rb -> **block in ms**
303:  /usr/local/rbenv/versions/2.2.2/lib/ruby/2.2.0/benchmark.rb -> **realtime**
12:  [GEM_ROOT]/gems/activesupport-4.2.3/lib/active_support/core_ext/benchmark.rb -> **ms**
44:  [GEM_ROOT]/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb -> **block in render**
87:  [GEM_ROOT]/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb -> **cleanup_view_runtime**
25:  [GEM_ROOT]/gems/activerecord-4.2.3/lib/active_record/railties/controller_runtime.rb -> **cleanup_view_runtime**
43:  [GEM_ROOT]/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb -> **render**
14:  [GEM_ROOT]/gems/remotipart-1.2.1/lib/remotipart/render_overrides.rb -> **render_with_remotipart**
10:  [GEM_ROOT]/gems/actionpack-4.2.3/lib/action_controller/metal/implicit_render.rb -> **default_render**
5:  [GEM_ROOT]/gems/actionpack-4.2.3/lib/action_controller/metal/implicit_render.rb -> **send_action**
198:  [GEM_ROOT]/gems/actionpack-4.2.3/lib/abstract_controller/base.rb -> **process_action**
10:  [GEM_ROOT]/gems/actionpack-4.2.3/lib/action_controller/metal/rendering.rb -> **process_action**
20:  [GEM_ROOT]/gems/actionpack-4.2.3/lib/abstract_controller/callbacks.rb -> **block in process_action**
115:  [GEM_ROOT]/gems/activesupport-4.2.3/lib/active_support/callbacks.rb -> **call**
115:  [GEM_ROOT]/gems/activesupport-4.2.3/lib/active_support/callbacks.rb -> **call**
553:  [GEM_ROOT]/gems/activesupport-4.2.3/lib/active_support/callbacks.rb -> **block (2 levels) in compile**
503:  [GEM_ROOT]/gems/activesupport-4.2.3/lib/active_support/callbacks.rb -> **call**
503:  [GEM_ROOT]/gems/activesupport-4.2.3/lib/active_support/callbacks.rb -> **call**
88:  [GEM_ROOT]/gems/activesupport-4.2.3/lib/active_support/callbacks.rb -> **run_callbacks**
19:  [GEM_ROOT]/gems/actionpack-4.2.3/lib/abstract_controller/callbacks.rb -> **process_action**
29:  [GEM_ROOT]/gems/actionpack-4.2.3/lib/action_controller/metal/rescue.rb -> **process_action**
32:  [GEM_ROOT]/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb -> **block in process_action**
164:  [GEM_ROOT]/gems/activesupport-4.2.3/lib/active_support/notifications.rb -> **block in instrument**
20:  [GEM_ROOT]/gems/activesupport-4.2.3/lib/active_support/notifications/instrumenter.rb -> **instrument**
164:  [GEM_ROOT]/gems/activesupport-4.2.3/lib/active_support/notifications.rb -> **instrument**
30:  [GEM_ROOT]/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb -> **process_action**
250:  [GEM_ROOT]/gems/actionpack-4.2.3/lib/action_controller/metal/params_wrapper.rb -> **process_action**
18:  [GEM_ROOT]/gems/activerecord-4.2.3/lib/active_record/railties/controller_runtime.rb -> **process_action**
137:  [GEM_ROOT]/gems/actionpack-4.2.3/lib/abstract_controller/base.rb -> **process**
30:  [GEM_ROOT]/gems/actionview-4.2.3/lib/action_view/rendering.rb -> **process**
77:  [GEM_ROOT]/gems/rack-mini-profiler-0.9.3/lib/mini_profiler/profiling_methods.rb -> **block in profile_method**
196:  [GEM_ROOT]/gems/actionpack-4.2.3/lib/action_controller/metal.rb -> **dispatch**
13:  [GEM_ROOT]/gems/actionpack-4.2.3/lib/action_controller/metal/rack_delegation.rb -> **dispatch**
237:  [GEM_ROOT]/gems/actionpack-4.2.3/lib/action_controller/metal.rb -> **block in action**
76:  [GEM_ROOT]/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb -> **call**
76:  [GEM_ROOT]/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb -> **dispatch**
45:  [GEM_ROOT]/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb -> **serve**
43:  [GEM_ROOT]/gems/actionpack-4.2.3/lib/action_dispatch/journey/router.rb -> **block in serve**
30:  [GEM_ROOT]/gems/actionpack-4.2.3/lib/action_dispatch/journey/router.rb -> **each**
30:  [GEM_ROOT]/gems/actionpack-4.2.3/lib/action_dispatch/journey/router.rb -> **serve**
821:  [GEM_ROOT]/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb -> **call**
67:  [GEM_ROOT]/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb -> **call**
12:  [GEM_ROOT]/gems/rack-pjax-0.8.0/lib/rack/pjax.rb -> **call**
67:  [GEM_ROOT]/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb -> **call**
30:  [GEM_ROOT]/gems/newrelic_rpm-3.12.0.288/lib/new_relic/rack/agent_hooks.rb -> **traced_call**
67:  [GEM_ROOT]/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb -> **call**
32:  [GEM_ROOT]/gems/newrelic_rpm-3.12.0.288/lib/new_relic/rack/browser_monitoring.rb -> **traced_call**
67:  [GEM_ROOT]/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb -> **call**
35:  [GEM_ROOT]/gems/warden-1.2.3/lib/warden/manager.rb -> **block in call**
34:  [GEM_ROOT]/gems/warden-1.2.3/lib/warden/manager.rb -> **catch**
34:  [GEM_ROOT]/gems/warden-1.2.3/lib/warden/manager.rb -> **call**
67:  [GEM_ROOT]/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb -> **call**
24:  [GEM_ROOT]/gems/rack-1.6.4/lib/rack/etag.rb -> **call**
67:  [GEM_ROOT]/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb -> **call**
25:  [GEM_ROOT]/gems/rack-1.6.4/lib/rack/conditionalget.rb -> **call**
67:  [GEM_ROOT]/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb -> **call**
13:  [GEM_ROOT]/gems/rack-1.6.4/lib/rack/head.rb -> **call**
67:  [GEM_ROOT]/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb -> **call**
27:  [GEM_ROOT]/gems/remotipart-1.2.1/lib/remotipart/middleware.rb -> **call**
67:  [GEM_ROOT]/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb -> **call**
27:  [GEM_ROOT]/gems/actionpack-4.2.3/lib/action_dispatch/middleware/params_parser.rb -> **call**
67:  [GEM_ROOT]/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb -> **call**
260:  [GEM_ROOT]/gems/actionpack-4.2.3/lib/action_dispatch/middleware/flash.rb -> **call**
67:  [GEM_ROOT]/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb -> **call**
225:  [GEM_ROOT]/gems/rack-1.6.4/lib/rack/session/abstract/id.rb -> **context**
220:  [GEM_ROOT]/gems/rack-1.6.4/lib/rack/session/abstract/id.rb -> **call**
67:  [GEM_ROOT]/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb -> **call**
560:  [GEM_ROOT]/gems/actionpack-4.2.3/lib/action_dispatch/middleware/cookies.rb -> **call**
67:  [GEM_ROOT]/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb -> **call**
36:  [GEM_ROOT]/gems/activerecord-4.2.3/lib/active_record/query_cache.rb -> **call**
67:  [GEM_ROOT]/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb -> **call**
653:  [GEM_ROOT]/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb -> **call**
67:  [GEM_ROOT]/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb -> **call**
29:  [GEM_ROOT]/gems/actionpack-4.2.3/lib/action_dispatch/middleware/callbacks.rb -> **block in call**
84:  [GEM_ROOT]/gems/activesupport-4.2.3/lib/active_support/callbacks.rb -> **run_callbacks**
27:  [GEM_ROOT]/gems/actionpack-4.2.3/lib/action_dispatch/middleware/callbacks.rb -> **call**
67:  [GEM_ROOT]/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb -> **call**
78:  [GEM_ROOT]/gems/actionpack-4.2.3/lib/action_dispatch/middleware/remote_ip.rb -> **call**
67:  [GEM_ROOT]/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb -> **call**
67:  [GEM_ROOT]/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb -> **call**
17:  [GEM_ROOT]/gems/actionpack-4.2.3/lib/action_dispatch/middleware/debug_exceptions.rb -> **call**
67:  [GEM_ROOT]/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb -> **call**
30:  [GEM_ROOT]/gems/actionpack-4.2.3/lib/action_dispatch/middleware/show_exceptions.rb -> **call**
67:  [GEM_ROOT]/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb -> **call**
38:  [GEM_ROOT]/gems/railties-4.2.3/lib/rails/rack/logger.rb -> **call_app**
22:  [GEM_ROOT]/gems/railties-4.2.3/lib/rails/rack/logger.rb -> **call**
67:  [GEM_ROOT]/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb -> **call**
8:  [GEM_ROOT]/gems/request_store-1.1.0/lib/request_store/middleware.rb -> **call**
67:  [GEM_ROOT]/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb -> **call**
21:  [GEM_ROOT]/gems/actionpack-4.2.3/lib/action_dispatch/middleware/request_id.rb -> **call**
67:  [GEM_ROOT]/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb -> **call**
22:  [GEM_ROOT]/gems/rack-1.6.4/lib/rack/methodoverride.rb -> **call**
67:  [GEM_ROOT]/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb -> **call**
18:  [GEM_ROOT]/gems/rack-1.6.4/lib/rack/runtime.rb -> **call**
67:  [GEM_ROOT]/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb -> **call**
28:  [GEM_ROOT]/gems/activesupport-4.2.3/lib/active_support/cache/strategy/local_cache_middleware.rb -> **call**
67:  [GEM_ROOT]/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb -> **call**
113:  [GEM_ROOT]/gems/rack-1.6.4/lib/rack/sendfile.rb -> **call**
67:  [GEM_ROOT]/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb -> **call**
67:  [GEM_ROOT]/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb -> **call**
167:  [GEM_ROOT]/gems/rack-mini-profiler-0.9.3/lib/mini_profiler/profiler.rb -> **call**
67:  [GEM_ROOT]/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb -> **call**
518:  [GEM_ROOT]/gems/railties-4.2.3/lib/rails/engine.rb -> **call**
165:  [GEM_ROOT]/gems/railties-4.2.3/lib/rails/application.rb -> **call**
67:  [GEM_ROOT]/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb -> **call**
66:  [GEM_ROOT]/gems/rack-1.6.4/lib/rack/urlmap.rb -> **block in call**
50:  [GEM_ROOT]/gems/rack-1.6.4/lib/rack/urlmap.rb -> **each**
50:  [GEM_ROOT]/gems/rack-1.6.4/lib/rack/urlmap.rb -> **call**
80:  [GEM_ROOT]/gems/rack-cors-0.4.0/lib/rack/cors.rb -> **call**
580:  [GEM_ROOT]/gems/unicorn-4.9.0/lib/unicorn/http_server.rb -> **process_client**
52:  [GEM_ROOT]/gems/unicorn-worker-killer-0.4.3/lib/unicorn/worker_killer.rb -> **process_client**
92:  [GEM_ROOT]/gems/unicorn-worker-killer-0.4.3/lib/unicorn/worker_killer.rb -> **process_client**
674:  [GEM_ROOT]/gems/unicorn-4.9.0/lib/unicorn/http_server.rb -> **worker_loop**
529:  [GEM_ROOT]/gems/unicorn-4.9.0/lib/unicorn/http_server.rb -> **spawn_missing_workers**
540:  [GEM_ROOT]/gems/unicorn-4.9.0/lib/unicorn/http_server.rb -> **maintain_worker_count**
294:  [GEM_ROOT]/gems/unicorn-4.9.0/lib/unicorn/http_server.rb -> **join**
209:  [GEM_ROOT]/gems/unicorn-4.9.0/bin/unicorn_rails -> **&lt;top (required)&gt;**
23:  [GEM_ROOT]/bin/unicorn_rails -> **load**
23:  [GEM_ROOT]/bin/unicorn_rails -> **&lt;main&gt;**
~~~

## Environment ##
| Key        | Value      |
|------------|------------|
| REMOTE_ADDR | 127.0.0.1 |
| REQUEST_METHOD | GET |
| REQUEST_PATH | /abilitysheet/rival/reverse_list |
| PATH_INFO | /rival/reverse_list |
| REQUEST_URI | /abilitysheet/rival/reverse_list |
| SERVER_PROTOCOL | HTTP/1.0 |
| HTTP_VERSION | HTTP/1.0 |
| HTTP_X_REAL_IP | 118.15.165.188 |
| HTTP_X_FORWARDED_FOR | 118.15.165.188 |
| HTTP_HOST | iidx12.tk |
| HTTP_CONNECTION | close |
| HTTP_ACCEPT | text/html, application/xhtml+xml, application/xml |
| HTTP_USER_AGENT | Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.130 Safari/537.36 |
| HTTP_X_XHR_REFERER | http://iidx12.tk/abilitysheet/ |
| HTTP_REFERER | http://iidx12.tk/abilitysheet/ |
| HTTP_ACCEPT_ENCODING | gzip, deflate, sdch |
| HTTP_ACCEPT_LANGUAGE | ja,en-US;q=0.8,en;q=0.6 |
| HTTP_IF_NONE_MATCH | W/&quot;fe3f17c3f2b0fa238d1a72bf03a02b58&quot; |
| rack_url_scheme | http |
| SERVER_NAME | iidx12.tk |
| SERVER_PORT | 80 |
| QUERY_STRING |  |
| rack_hijack | #&lt;Proc:0x007efd0db15fb0@/home/rails/deploy/abilitysheet/shared/bundle/ruby/2.2.0/gems/unicorn-4.9.0/lib/unicorn/http_request.rb:111&gt; |
| rack_multiprocess | true |
| rack_multithread | false |
| rack_run_once | false |
| rack_version | [&quot;1&quot;, &quot;2&quot;] |
| SCRIPT_NAME | /abilitysheet |
| SERVER_SOFTWARE | Unicorn 4.9.0 |
| rack_hijack? | true |
| rack_logger | #&lt;Logger:0x007efd092776a0&gt; |
| rack_cors | #&lt;Rack::Cors::Result:0x007efd0db15f10&gt; |
| newrelic_transaction_started | true |
| ORIGINAL_FULLPATH | /abilitysheet/rival/reverse_list |
| ORIGINAL_SCRIPT_NAME | /abilitysheet |
| action_dispatch_parameter_filter | [&quot;password&quot;] |
| action_dispatch_redirect_filter | [] |
| action_dispatch_show_exceptions | true |
| action_dispatch_show_detailed_exceptions | false |
| action_dispatch_cookies_serializer | json |
| action_dispatch_cookies_digest |  |
| ROUTES_69812664178100_SCRIPT_NAME | /abilitysheet |
| action_dispatch_request_id | c3228424-2547-413a-9856-c69d1f6d0862 |
| action_dispatch_remote_ip | 118.15.165.188 |
| rack_request_query_string |  |
| rack_request_query_hash |  |
| warden | Warden::Proxy:69812660726080 @config={:default_scope=&gt;:user, :scope_defaults=&gt;{}, :default_strategies=&gt;{:user=&gt;[:rememberable, :database_authenticatable]}, :intercept_401=&gt;false, :failure_app=&gt;#&lt;Devise::Delegator:0x007efd0cf61bd8&gt;} |
| action_dispatch_request_path_parameters | {&quot;controller&quot;=&gt;&quot;rivals&quot;, &quot;action&quot;=&gt;&quot;reverse_list&quot;} |
| action_dispatch_request_content_type |  |
| action_dispatch_request_request_parameters |  |
| action_dispatch_request_query_parameters |  |
| action_dispatch_request_parameters | {&quot;controller&quot;=&gt;&quot;rivals&quot;, &quot;action&quot;=&gt;&quot;reverse_list&quot;} |
| action_dispatch_request_accepts | [&quot;text/html&quot;, &quot;application/xml&quot;] |
| action_dispatch_request_formats | [&quot;text/html&quot;, &quot;application/xml&quot;] |

### PR DESCRIPTION
**Pull request by 8398a7**

### CODE REVIEW

File: app/models/user.rb [hunk 1]
```diff
@@ -103,6 +94,16 @@ def belongs
       Static::PREF.each_with_index { |p, i| array.push([p, i]) }
       array
     end
+
+    def find_first_by_auth_conditions(warden_conditions)
```
Comment (8398a7) [inline app/models/user.rb]: __[rails_best_practices]__
* remove unused methods (User#find_first_by_auth_conditions)
